# Generated by Django 3.2.11 on 2023-08-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liveroom',
            fields=[
                ('roomID', models.AutoField(primary_key=True, serialize=False, verbose_name='roomID')),
                ('roomName', models.CharField(max_length=100, verbose_name='roomName')),
                ('roomInfo', models.CharField(max_length=2048, verbose_name='roomInfo')),
                ('roomcover', models.ImageField(upload_to='livecover/', verbose_name='roomcover')),
                ('roomstatus', models.BooleanField(default=False, verbose_name='roomstatus')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='Owner')),
            ],
            options={
                'db_table': '直播间表',
            },
        ),
    ]
