# Generated by Django 3.2.11 on 2023-05-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_Favorite_Table',
            fields=[
                ('Act_id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(choices=[('like', '点赞'), ('favorite', '收藏')], max_length=255)),
                ('DV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='video.video')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Table',
            fields=[
                ('Comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.CharField(max_length=1023, verbose_name='评论')),
                ('Time', models.DateTimeField(auto_now_add=True, max_length=255)),
                ('DV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='video.video')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attention_Table',
            fields=[
                ('Attention_id', models.AutoField(primary_key=True, serialize=False)),
                ('Up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='User.user')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='User.user')),
            ],
        ),
    ]
