# Generated by Django 3.2.11 on 2023-07-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
