# Generated by Django 3.2.11 on 2023-07-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='NickName',
            field=models.CharField(default='New User', max_length=15),
        ),
    ]
