# Generated by Django 3.2.11 on 2023-05-16 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('Ccode', models.AutoField(primary_key=True, serialize=False, verbose_name='视频分区号')),
                ('Title', models.CharField(max_length=20, verbose_name='视频分区')),
            ],
            options={
                'db_table': '视频分区',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('DVcode', models.AutoField(primary_key=True, serialize=False, verbose_name='视频号')),
                ('Title', models.CharField(max_length=100, verbose_name='视频名称')),
                ('ReleaseTime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('Viewsnum', models.BigIntegerField(default=0, verbose_name='播放量')),
                ('Content', models.CharField(default='该用户很懒，it什么也没有说！', max_length=500, verbose_name='视频简介')),
                ('VideoFile', models.FileField(upload_to='video/', validators=[django.core.validators.FileExtensionValidator(['mp4'])], verbose_name='视频文件')),
                ('CoverFile', models.ImageField(upload_to='cover/', verbose_name='封面文件')),
                ('Classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.classification', verbose_name='分区')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='作者')),
            ],
            options={
                'db_table': '视频',
            },
        ),
    ]
